name: build-and-release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: Install Setuptools
        run: python3 -m pip install setuptools --break-system-packages

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v4
        with:
          name: Flow_${{ matrix.os }}
          path: ./build/
