name: build-and-release

on:
  push:
    #tags:
    #- "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: Install Setuptools
        run: python3 -m pip install setuptools --break-system-packages

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v4
        with:
          name: Dish_Deception_Win
          path: ./build/win_amd64/

  build-macos:
    runs-on: macos-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install panda
        run: python3 -m pip install -r requirements.txt --break-system-packages

      - name: Install Setuptools
        run: python3 -m pip install setuptools --break-system-packages

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v4
        with:
          name: Dish_Deception_OSX
          path: ./build/macosx_10_9_x86_64/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: Install Setuptools
        run: python3 -m pip install setuptools --break-system-packages

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v4
        with:
          name: Dish_Deception_Linux
          path: ./build/manylinux2010_x86_64/ 

  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: build

      - run: zip -r linux.zip build/Pyweek39_Linux

      - run: zip -r windows.zip build/Pyweek39_Win

      - run: zip -r macos.zip build/Pyweek39_OSX

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux.zip
            macos.zip
            windows.zip
