name: build-and-release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: Install Setuptools
        run: python3 -m pip install setuptools --break-system-packages

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v4
        with:
          name: Dish_Deception_Win
          path: ./build/win_amd64/
