name: build-and-release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: Install Setuptools
        run: python3 -m pip install setuptools --break-system-packages

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v4
        with:
          name: flow_${{ matrix.os }}
          path: ./build/

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: build

      - run: zip -r linux.zip build/flow_ubuntu

      - run: zip -r windows.zip build/flow_windows

      - run: zip -r macos.zip build/flow_macos

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux.zip
            macos.zip
            windows.zip
